language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t komal96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true komal96/react-test npm test

after_success:
  - docker build -t komal96/multi-client ./client
  - docker build -t komal96/multi-nginx ./nginx
  - docker build -t komal96/multi-server ./server
  - docker build -t komal96/multi-worker ./worker
  # login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # take those images and push them to docker hub

  - docker push komal96/multi-client
  - docker push komal96/multi-nginx
  - docker push komal96/multi-server
  - docker push komal96/multi-worker
