language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t kapp96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kapp96/react-test npm test

after_success:
  - docker build -t kapp96/multi-client ./client
  - docker build -t kapp96/multi-nginx ./nginx
  - docker build -t kapp96/multi-server ./server
  - docker build -t kapp96/multi-worker ./worker